services:
  - type: web
    name: deepfake-detector-ai-v1
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    # Port configuration is handled automatically by Render
