services:
  - type: web
    name: deepfake-detector-ai-v1
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app --timeout 120 --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
